/*
 * Copyright 2018 Dmitry Avtonomov.
 *
 * Licensed under the Apache License, Version 2.0 (the "License");
 * you may not use this file except in compliance with the License.
 * You may obtain a copy of the License at
 *
 *      http://www.apache.org/licenses/LICENSE-2.0
 *
 * Unless required by applicable law or agreed to in writing, software
 * distributed under the License is distributed on an "AS IS" BASIS,
 * WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
 * See the License for the specific language governing permissions and
 * limitations under the License.
 */
package test.swing;

import javax.swing.JButton;
import javax.swing.JLabel;
import javax.swing.JPanel;
import javax.swing.JTextField;
import net.miginfocom.swing.MigLayout;

/**
 *
 * @author Dmitry Avtonomov
 */
public class NewJFrame extends javax.swing.JFrame {
    
    JLabel settingsLabel = new JLabel("Dashboard Settings");
    JLabel nameLabel = new JLabel("Name:");
    JLabel zipLabel = new JLabel("Zip Code:");
    JLabel emailLabel = new JLabel("Email:");
    JLabel avatarLabel = new JLabel("Avatar Image:");
    JTextField fNameField = new JTextField(10);
    JTextField mNameField = new JTextField(1);
    JTextField lNameField = new JTextField(15);
    JTextField zipField = new JTextField(5);
    JTextField emailField = new JTextField(20);
    JTextField avatarField = new JTextField(30);
    JButton okBttn = new JButton("Ok");
    JButton cancelBttn = new JButton("Cancel");
    JButton helpBttn = new JButton("Help");

    /**
     * Creates new form NewJFrame
     */
    public NewJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        addWindowListener(new java.awt.event.WindowAdapter() {
            public void windowOpened(java.awt.event.WindowEvent evt) {
                formWindowOpened(evt);
            }
        });

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 400, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 300, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void formWindowOpened(java.awt.event.WindowEvent evt) {//GEN-FIRST:event_formWindowOpened
        JPanel panel = buildMiGDashboard();      
        this.add(panel);
        this.pack();
        this.setVisible(true);
    }//GEN-LAST:event_formWindowOpened

    

    private JPanel buildMiGDashboard() {
        JPanel panel = new JPanel();
        panel.setLayout(new MigLayout());
        buildMiGForm(panel);
        return panel;
    }

    private void buildMiGForm(JPanel panel) {
        panel.add(settingsLabel, "span, center, gapbottom 15");
        panel.add(nameLabel, "align label");
        panel.add(fNameField);
        panel.add(mNameField);

        //wrap keyword starts a new row
        panel.add(lNameField, "wrap");

        //align label triggers platform-specific label alignment
        panel.add(zipLabel, "align label");
        panel.add(zipField, "wrap");
        panel.add(emailLabel,"align label");

        //span keyword lets emailField use the rest of the row
        panel.add(emailField, "span");
        panel.add(avatarLabel, "align label");
        panel.add(avatarField, "span");

        //tag identifies the type of button
        panel.add(okBttn, "tag ok, span, split 3, sizegroup bttn");

        //sizegroups set all members to the size of the biggest member
        panel.add(cancelBttn, "tag cancel, sizegroup bttn");
        panel.add(helpBttn, "tag help, sizegroup bttn");
    }
    
    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(NewJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new NewJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    // End of variables declaration//GEN-END:variables
}
