# Workflow: Defaults

crystalc.correct_isotope_error=false
crystalc.isotope_number=3
crystalc.max-charge=6
crystalc.precursor_isolation_window=0.7
crystalc.precursor_mass=20
crystalc.run-crystalc=false
database.decoy-tag=rev_
freequant.mz-tol=10
freequant.rt-tol=0.4
freequant.run-freequant=true
ionquant.im-tol=0.05
ionquant.is-plot=false
ionquant.min-freq=0.50
ionquant.mz-tol=10
ionquant.rt-tol=0.4
ionquant.run-ionquant=false
msfragger.add_topN_complementary=0
msfragger.allow_multiple_variable_mods_on_residue=false
msfragger.allowed_missed_cleavage=1
msfragger.calibrate_mass=Off
msfragger.clip_nTerm_M=false
msfragger.deisotope=1
msfragger.delta_mass_exclude_ranges=(-1.5,3.5)
msfragger.digest_max_length=50
msfragger.digest_min_length=7
msfragger.fragment_ion_series=
msfragger.fragment_mass_tolerance=10
msfragger.fragment_mass_units=PPM
msfragger.intensity_transform=None
msfragger.ion_series_definitions=
msfragger.isotope_error=
msfragger.localize_delta_mass=false
msfragger.mass_offsets=<html>\n  <head>\n    \n  </head>\n  <body>\n  </body>\n</html>\n
msfragger.max_fragment_charge=2
msfragger.max_variable_mods_combinations=5000
msfragger.max_variable_mods_per_peptide=3
msfragger.min_fragments_modelling=2
msfragger.min_matched_fragments=4
msfragger.minimum_peaks=15
msfragger.minimum_ratio=0.01
msfragger.misc.fragger.clear-mz-hi=0
msfragger.misc.fragger.clear-mz-lo=0
msfragger.misc.fragger.digest-mass-hi=5000
msfragger.misc.fragger.digest-mass-lo=200
msfragger.misc.fragger.enzyme-dropdown=trypsin
msfragger.misc.fragger.precursor-charge-hi=4
msfragger.misc.fragger.precursor-charge-lo=1
msfragger.misc.fragger.remove-precursor-range-hi=1.5
msfragger.misc.fragger.remove-precursor-range-lo=-1.5
msfragger.misc.slice-db=1
msfragger.num_enzyme_termini=ENZYMATIC
msfragger.output_format=PEP_XML
msfragger.output_max_expect=50
msfragger.output_report_topN=1
msfragger.override_charge=false
msfragger.precursor_mass_lower=-10
msfragger.precursor_mass_mode=selected
msfragger.precursor_mass_units=PPM
msfragger.precursor_mass_upper=10
msfragger.precursor_true_tolerance=10
msfragger.precursor_true_units=PPM
msfragger.remove_precursor_peak=Do not remove
msfragger.report_alternative_proteins=false
msfragger.run-msfragger=true
msfragger.search_enzyme_butnotafter=P
msfragger.search_enzyme_cutafter=KR
msfragger.search_enzyme_name=
msfragger.table.fix-mods=0.00000,C-Term Peptide,true,-1; 0.00000,N-Term Peptide,true,-1; 0.00000,C-Term Protein,true,-1; 0.00000,N-Term Protein,true,-1; 0.00000,G (glycine),true,-1; 0.00000,A (alanine),true,-1; 0.00000,S (serine),true,-1; 0.00000,P (proline),true,-1; 0.00000,V (valine),true,-1; 0.00000,T (threonine),true,-1; 57.02146,C (cysteine),true,-1; 0.00000,L (leucine),true,-1; 0.00000,I (isoleucine),true,-1; 0.00000,N (asparagine),true,-1; 0.00000,D (aspartic acid),true,-1; 0.00000,Q (glutamine),true,-1; 0.00000,K (lysine),true,-1; 0.00000,E (glutamic acid),true,-1; 0.00000,M (methionine),true,-1; 0.00000,H (histidine),true,-1; 0.00000,F (phenylalanine),true,-1; 0.00000,R (arginine),true,-1; 0.00000,Y (tyrosine),true,-1; 0.00000,W (tryptophan),true,-1; 0.00000,B ,true,-1; 0.00000,J,true,-1; 0.00000,O,true,-1; 0.00000,U,true,-1; 0.00000,X,true,-1; 0.00000,Z,true,-1
msfragger.table.var-mods=15.99490,M,true,3; 42.01060,[^,true,1; 79.96633,STY,false,3; -17.02650,nQnC,false,1; -18.01060,nE,false,1; 0.00000,site_06,false,1; 0.00000,site_07,false,1; 0.00000,site_08,false,1; 0.00000,site_09,false,1; 0.00000,site_10,false,1; 0.00000,site_11,false,1; 0.00000,site_12,false,1; 0.00000,site_13,false,1; 0.00000,site_14,false,1; 0.00000,site_15,false,1; 0.00000,site_16,false,1
msfragger.track_zero_topN=0
msfragger.use_topN_peaks=100
msfragger.zero_bin_accept_expect=0.00
msfragger.zero_bin_mult_expect=1.00
peptide-prophet.cmd-opts=--decoyprobs --ppm --accmass --nonparam --expectscore
peptide-prophet.combine-pepxml=false
peptide-prophet.run-peptide-prophet=true
phi-report.dont-use-prot-proph-file=false
phi-report.filter=--sequential --razor --prot 0.01
phi-report.multi-exp-report=false
phi-report.pep-level-summary=false
phi-report.print-decoys=false
phi-report.run-report=true
phi-report.write-mzid=false
protein-prophet.cmd-opts=--maxppmdiff 2000000
protein-prophet.run-protein-prophet=true
ptmshepherd.histo_smoothbins=2
ptmshepherd.localization_background=4
ptmshepherd.output_extended=false
ptmshepherd.peakpicking_promRatio=0.3
ptmshepherd.peakpicking_width=0.002
ptmshepherd.run-shepherd=false
ptmshepherd.varmod_masses=
quantitation.run-label-free-quant=false
speclibgen.run-speclibgen=false
speclibgen.ui.name.report.speclibgen.easypqp.data-type=timsTOF
speclibgen.ui.name.report.speclibgen.easypqp.rt-cal=Automatic selection of a run as reference RT
speclibgen.use-easypqp=false
speclibgen.use-spectrast=true
tmtintegrator.add_Ref=Reference sample
tmtintegrator.allow_overlabel=true
tmtintegrator.allow_unlabeled=true
tmtintegrator.best_psm=true
tmtintegrator.channel_num=TMT-6
tmtintegrator.freequant=--ptw 0.4 --tol 10 --isolated
tmtintegrator.groupby=Gene level
tmtintegrator.labelquant=--purity 0.5 --tol 10
tmtintegrator.min_pep_prob=0.9
tmtintegrator.min_percent=0.5
tmtintegrator.min_purity=0.5
tmtintegrator.min_site_prob=-1
tmtintegrator.mod_tag=none
tmtintegrator.ms1_int=true
tmtintegrator.outlier_removal=true
tmtintegrator.print_RefInt=false
tmtintegrator.prot_exclude=none
tmtintegrator.prot_norm=None
tmtintegrator.psm_norm=false
tmtintegrator.ref_tag=Bridge
tmtintegrator.run-tmtintegrator=false
tmtintegrator.top3_pep=true
tmtintegrator.unique_gene=Leave all PSMs
tmtintegrator.unique_pep=false
workflow.workflow-option=Defaults
